// <auto-generated />
namespace WorkFlowManager.Common.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddHierarchyExplorerForm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHierarchyExplorerForm));
        
        string IMigrationMetadata.Id
        {
            get { return "202106281614167_AddHierarchyExplorerForm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
